# Generated by Django 3.2.6 on 2021-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='Due',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='Paid',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
