# Generated by Django 3.2.6 on 2021-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='Department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='Session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
