# Generated by Django 3.2 on 2021-10-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEERP', '0002_auto_20211030_1204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userstudent',
            table='userstudent',
        ),
    ]
