# Generated by Django 3.2.6 on 2021-10-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEERP', '0002_auto_20211019_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='SSC_Registration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='SSC_Roll',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='Student_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
