# Generated by Django 3.2 on 2021-10-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEERP', '0003_alter_userstudent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='Section',
            field=models.CharField(default='', max_length=50),
        ),
    ]
