# Generated by Django 3.2.6 on 2021-10-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEERP', '0004_auto_20211023_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteacher',
            name='BIO_DATA',
            field=models.TextField(default=''),
        ),
    ]
